# Generated by Django 5.2.6 on 2025-11-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='splits',
            old_name='creator_id',
            new_name='user',
        ),
    ]
