# Generated by Django 5.2.6 on 2025-12-19 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splits', '0002_rename_creator_id_splits_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='splits',
        #     name='status',
        #     field=models.CharField(default='active', max_length=10),
        # ),
        migrations.CreateModel(
            name='SplitParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_amount', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('split', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splits.splits')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
