# Generated by Django 5.2.6 on 2025-11-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='expiry_at',
            field=models.DateTimeField(),
        ),
    ]
