# Generated by Django 5.2.6 on 2025-11-18 14:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='nationality'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='expiry_at',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('full_address', models.TextField()),
                ('document_type', models.CharField(choices=[('national_id', 'National ID Card'), ('drivers_license', "Driver's License"), ('passport', 'International Passport')], max_length=50)),
                ('document_file', models.FileField(upload_to='kyc_documents/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_by_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(help_text='The user who submitted this KYC record.', on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('split_created', 'Split Created'), ('split_updated', 'Split Updated'), ('split_joined', 'Split Joined'), ('split_deleted', 'Split Deleted'), ('account_updated', 'Account Updated'), ('kyc_completed', 'KYC Completed'), ('payement_recieved', 'Payment Recieved')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='users_notif_user_id_2c9cd4_idx'), models.Index(fields=['user', 'read_at'], name='users_notif_user_id_02c2a2_idx')],
            },
        ),
    ]
