# Generated by Django 5.2.6 on 2025-11-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_emailotp_expiry_at'),
        ('users', '0005_rename_text_notification_message'),
    ]

    operations = [
    ]
