# Generated by Django 5.2.6 on 2025-11-13 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('full_address', models.TextField()),
                ('document_type', models.CharField(choices=[('national_id', 'National ID Card'), ('drivers_license', "Driver's License"), ('passport', 'International Passport')], max_length=50)),
                ('document_file', models.FileField(upload_to='kyc_documents/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_by_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(help_text='The user who submitted this KYC record.', on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
