# Generated by Django 5.2.6 on 2025-11-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycverification',
            name='document_file',
        ),
        migrations.AddField(
            model_name='kycverification',
            name='document_back',
            field=models.FileField(blank=True, null=True, upload_to='kyc_documents/'),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='document_front',
            field=models.FileField(blank=True, null=True, upload_to='kyc_documents/'),
        ),
    ]
